Repository RawitSHIE/HotelVendor, pull requests merged in 2019-11, with the labels that each got.

#17 Update booking model
  booking/src/main/java/sop/project/booking/BookingController.java
  booking/src/main/java/sop/project/booking/ServiceDiscoveryClient.java
  booking/src/main/java/sop/project/booking/exception/NotFoundException.java
  booking/src/main/java/sop/project/booking/model/Booking.java
  booking/src/main/java/sop/project/booking/model/RoomTypeDetail.java
  booking/src/main/java/sop/project/booking/model/extendModel/BookingRoomDetail.java
  booking/src/main/java/sop/project/booking/model/extendModel/BookingStatus.java
  booking/src/main/java/sop/project/booking/model/extendModel/requestModel/Hotel.java
  booking/src/main/java/sop/project/booking/model/extendModel/requestModel/HotelFullDetail.java
  booking/src/main/java/sop/project/booking/model/extendModel/requestModel/RoomType.java
  booking/src/main/java/sop/project/booking/model/extendModel/requestModel/RoomTypeRequest.java
  booking/src/main/java/sop/project/booking/model/extendModel/requestModel/User.java
  booking/src/main/java/sop/project/booking/model/extendModel/response/BookingFullDetail.java
  booking/src/main/java/sop/project/booking/repository/RoomTypeDetailRepository.java
  hotel/src/main/java/sop/project/hotel/HotelController.java
  hotel/src/main/java/sop/project/hotel/model/responseModel/HotelFullDetail.java
Labels: enhancement

#19 Create create booking mechanism
  booking/src/main/java/sop/project/booking/BookingController.java
  booking/src/main/java/sop/project/booking/model/Booking.java
  booking/src/main/java/sop/project/booking/model/extendModel/BookingRoomDetail.java
  booking/src/main/java/sop/project/booking/model/extendModel/requestModel/SelectDate.java
Labels: enhancement

#27 update-hotel-with-auth
  hotel/pom.xml
  hotel/src/main/java/sop/project/hotel/HotelController.java
  hotel/src/main/java/sop/project/hotel/ServiceDiscoveryClient.java
  user/src/main/java/com/spring/restApiMysql/UserController.java
Labels: enhancement

#29 Update hotel front end
  front_hotel/css/index_css.css
  front_hotel/css/login_css.css
  front_hotel/css/reserve_css.css
  front_hotel/css/room_css.css
  front_hotel/dashboard.html
  front_hotel/index.html
  front_hotel/invoice.html
  front_hotel/login.html
  front_hotel/register.html
  front_hotel/reserve.html
  front_hotel/room.html
Labels: enhancement

#32 Update zuul gateway
  gateway/src/main/resources/application.yml
  hotel/src/main/java/sop/project/hotel/HotelController.java
  hotel/src/main/java/sop/project/hotel/ServiceDiscoveryClient.java
Labels: enhancement

#33 Fix update room type detail
  hotel/src/main/java/sop/project/hotel/HotelController.java
  hotel/src/main/java/sop/project/hotel/model/RoomType.java
Labels: bug

#34 Added search booking by userid
  booking/src/main/java/sop/project/booking/BookingController.java
Labels: bug, enhancement

#35 Added httpstatus
  booking/src/main/java/sop/project/booking/BookingController.java
Labels: enhancement

#37 added response entity
  hotel/src/main/java/sop/project/hotel/HotelController.java
Labels: enhancement

#38 Emergency booking status change cancel
  booking/src/main/java/sop/project/booking/BookingController.java
  booking/src/main/java/sop/project/booking/model/extendModel/BookingStatus.java
Labels: enhancement
